#!/usr/bin/env sh

# Function to switch between Colima, Podman, and native Docker
# Works in any POSIX-style shell (bash, zsh, etc)
# Add to ~/.zshrc or ~/.bashrc

# Configuration file to persist backend selection
DOCKER_ENV_CONFIG="${HOME}/.config/shell/docker-env-backend"

# Load persisted backend selection if it exists
if [ -f "${DOCKER_ENV_CONFIG}" ]; then
  . "${DOCKER_ENV_CONFIG}"
fi

docker-env() {
  case "$1" in
    colima)
      if ! command -v colima >/dev/null 2>&1; then
        echo "❌ Colima is not installed. Install with: brew install colima"
        return 1
      fi
      local sock="${HOME}/.colima/default/docker.sock"
      # Ensure Colima is running
      if ! colima status 2>&1 | grep -qi 'running'; then
        echo "❌ Colima is not running. Start it with: colima start"
        return 1
      fi
      # Ensure socket exists
      if [ ! -S "$sock" ]; then
        echo "❌ Colima socket not found at $sock"
        echo "   Try: colima start"
        return 1
      fi
      export DOCKER_HOST="unix://$sock"
      export DOCKER_BACKEND="colima"
      
      # Persist the selection
      mkdir -p "$(dirname "${DOCKER_ENV_CONFIG}")"
      cat > "${DOCKER_ENV_CONFIG}" << EOF
# Docker environment backend selection
# Auto-generated by docker-env - do not edit manually
export DOCKER_HOST="unix://$sock"
export DOCKER_BACKEND="colima"
EOF
      
      echo "🐳 Docker CLI now points to Colima ($sock)"
      echo "✓ Selection saved - will be loaded in new shell sessions"
      ;;
    podman)
      if ! command -v podman >/dev/null 2>&1; then
        echo "❌ Podman is not installed."
        if [ "$(uname)" = "Darwin" ]; then
          echo "   Install with: brew install podman"
        else
          echo "   Install with your system package manager (e.g., apt-get install podman)"
        fi
        return 1
      fi
      
      # Detect OS and set appropriate socket path
      local sock=""
      if [ "$(uname)" = "Darwin" ]; then
        # macOS: Podman machine socket
        sock="${HOME}/.local/share/containers/podman/machine/podman.sock"
        # Ensure Podman machine is running (commented out for now, but can be enabled)
        if podman machine list --format json 2>/dev/null | grep -qi running; then
         :
        elif podman machine list 2>/dev/null | grep -qi running; then
         :
        else
         echo "❌ Podman machine is not running. Start it with: podman machine start"
         return 1
        fi
      else
        # Linux: Try to detect rootless Podman socket
        # On Linux, Podman rootless typically uses /run/user/$(id -u)/podman/podman.sock
        # But we can also let Podman use its default (no DOCKER_HOST needed)
        local user_sock="/run/user/$(id -u)/podman/podman.sock"
        if [ -S "$user_sock" ]; then
          sock="$user_sock"
        else
          # On Linux, Podman often works without setting DOCKER_HOST
          # Just set BACKEND and let Podman use its default socket
          export DOCKER_BACKEND="podman"
          mkdir -p "$(dirname "${DOCKER_ENV_CONFIG}")"
          cat > "${DOCKER_ENV_CONFIG}" << EOF
# Docker environment backend selection
# Auto-generated by docker-env - do not edit manually
# On Linux, Podman uses default socket - no DOCKER_HOST needed
export DOCKER_BACKEND="podman"
EOF
          echo "🐙 Docker CLI now points to Podman (using default socket)"
          echo "✓ Selection saved - will be loaded in new shell sessions"
          return 0
        fi
      fi
      
      # For macOS or Linux with detected socket
      if [ -n "$sock" ]; then
        # Ensure socket exists (only check on macOS where it's required)
        if [ "$(uname)" = "Darwin" ] && [ ! -S "$sock" ]; then
          echo "❌ Podman socket not found at $sock"
          echo "   Try: podman machine start"
          return 1
        fi
        export DOCKER_HOST="unix://$sock"
      fi
      export DOCKER_BACKEND="podman"
      
      # Persist the selection
      mkdir -p "$(dirname "${DOCKER_ENV_CONFIG}")"
      if [ -n "$sock" ]; then
        cat > "${DOCKER_ENV_CONFIG}" << EOF
# Docker environment backend selection
# Auto-generated by docker-env - do not edit manually
export DOCKER_HOST="unix://$sock"
export DOCKER_BACKEND="podman"
EOF
        echo "🐙 Docker CLI now points to Podman ($sock)"
      else
        cat > "${DOCKER_ENV_CONFIG}" << EOF
# Docker environment backend selection
# Auto-generated by docker-env - do not edit manually
export DOCKER_BACKEND="podman"
EOF
        echo "🐙 Docker CLI now points to Podman (using default socket)"
      fi
      echo "✓ Selection saved - will be loaded in new shell sessions"
      ;;
    docker)
      # Native Docker - primarily for Linux where Docker runs natively
      if ! command -v docker >/dev/null 2>&1; then
        echo "❌ Docker is not installed."
        if [ "$(uname)" = "Darwin" ]; then
          echo "   On macOS, use 'docker-env colima' or 'docker-env podman' instead."
          echo "   Or install Docker Desktop from: https://www.docker.com/products/docker-desktop"
        else
          echo "   Install with your system package manager:"
          echo "     Ubuntu/Debian: sudo apt-get install docker.io docker-compose-v2"
          echo "     Fedora/RHEL:   sudo dnf install docker docker-compose-plugin"
          echo "     Arch:          sudo pacman -S docker docker-compose"
        fi
        return 1
      fi
      
      # Check if Docker daemon is running
      if ! docker info >/dev/null 2>&1; then
        echo "❌ Docker daemon is not running."
        if [ "$(uname)" = "Linux" ]; then
          echo "   Start it with: sudo systemctl start docker"
          echo "   Enable on boot: sudo systemctl enable docker"
          echo ""
          echo "   For rootless Docker, ensure the user service is running:"
          echo "     systemctl --user start docker"
        else
          echo "   Start Docker Desktop or the Docker daemon."
        fi
        return 1
      fi
      
      # Check if user can access Docker without sudo
      if [ "$(uname)" = "Linux" ]; then
        if ! docker ps >/dev/null 2>&1; then
          echo "⚠️  Cannot access Docker. You may need to:"
          echo "   1. Add your user to the docker group: sudo usermod -aG docker \$USER"
          echo "   2. Log out and back in (or run: newgrp docker)"
          echo ""
          echo "   Alternatively, use rootless Docker:"
          echo "     https://docs.docker.com/engine/security/rootless/"
          return 1
        fi
      fi
      
      # Detect socket path
      local sock="/var/run/docker.sock"
      
      # Check for rootless Docker socket on Linux
      if [ "$(uname)" = "Linux" ]; then
        local rootless_sock="${XDG_RUNTIME_DIR:-/run/user/$(id -u)}/docker.sock"
        if [ -S "$rootless_sock" ]; then
          sock="$rootless_sock"
        fi
      fi
      
      # Unset DOCKER_HOST to use the default socket, or set if using non-default
      if [ "$sock" = "/var/run/docker.sock" ]; then
        unset DOCKER_HOST
        export DOCKER_BACKEND="docker"
        
        mkdir -p "$(dirname "${DOCKER_ENV_CONFIG}")"
        cat > "${DOCKER_ENV_CONFIG}" << EOF
# Docker environment backend selection
# Auto-generated by docker-env - do not edit manually
# Using native Docker with default socket
export DOCKER_BACKEND="docker"
EOF
        echo "🐳 Docker CLI now uses native Docker (/var/run/docker.sock)"
      else
        export DOCKER_HOST="unix://$sock"
        export DOCKER_BACKEND="docker"
        
        mkdir -p "$(dirname "${DOCKER_ENV_CONFIG}")"
        cat > "${DOCKER_ENV_CONFIG}" << EOF
# Docker environment backend selection
# Auto-generated by docker-env - do not edit manually
export DOCKER_HOST="unix://$sock"
export DOCKER_BACKEND="docker"
EOF
        echo "🐳 Docker CLI now uses native Docker ($sock)"
      fi
      echo "✓ Selection saved - will be loaded in new shell sessions"
      ;;
    default)
      unset DOCKER_HOST
      unset DOCKER_BACKEND
      
      # Remove persisted selection
      if [ -f "${DOCKER_ENV_CONFIG}" ]; then
        rm -f "${DOCKER_ENV_CONFIG}"
      fi
      
      echo "🔄 Docker CLI reset to system default (/var/run/docker.sock)"
      echo "✓ Selection cleared - will not persist to new shell sessions"
      ;;
    status)
      echo "Current DOCKER_HOST: ${DOCKER_HOST:-/var/run/docker.sock (default)}"
      echo "DOCKER_BACKEND: ${DOCKER_BACKEND:-<not set>}"
      if [ -f "${DOCKER_ENV_CONFIG}" ]; then
        echo "Persisted: Yes (in ~/.config/shell/docker-env-backend)"
      else
        echo "Persisted: No"
      fi
      echo ""
      echo "System info:"
      echo "  OS: $(uname -s)"
      if [ "$(uname)" = "Linux" ]; then
        if [ -f /etc/os-release ]; then
          # Safely extract PRETTY_NAME or ID from /etc/os-release
          PRETTY_NAME=$(grep '^PRETTY_NAME=' /etc/os-release | head -n1 | cut -d= -f2- | sed 's/^"\(.*\)"$/\1/')
          ID_NAME=$(grep '^ID=' /etc/os-release | head -n1 | cut -d= -f2- | sed 's/^"\(.*\)"$/\1/')
          echo "  Distribution: ${PRETTY_NAME:-$ID_NAME}"
        fi
      fi
      echo ""
      echo "Available backends:"
      command -v docker >/dev/null 2>&1 && echo "  ✓ docker (native)" || echo "  ✗ docker (not installed)"
      command -v colima >/dev/null 2>&1 && echo "  ✓ colima" || echo "  ✗ colima (not installed)"
      command -v podman >/dev/null 2>&1 && echo "  ✓ podman" || echo "  ✗ podman (not installed)"
      echo ""
      echo "Active engine:"
      docker info --format '{{.Name}} ({{.OperatingSystem}})' 2>/dev/null || echo "  No active engine or cannot connect"
      ;;
    *)
      echo "Usage: docker-env {docker|colima|podman|default|status}"
      echo ""
      echo "Commands:"
      echo "  docker   - Use native Docker (recommended for Linux)"
      echo "  colima   - Switch to Colima backend (recommended for macOS)"
      echo "  podman   - Switch to Podman backend"
      echo "  default  - Reset to system default (clears persistence)"
      echo "  status   - Show current backend configuration"
      echo ""
      echo "Platform recommendations:"
      echo "  Linux:  docker-env docker"
      echo "  macOS:  docker-env colima (or docker-env podman)"
      ;;
  esac
}
