source 'https://rubygems.org'

gem 'rails', '4.2.5'
gem 'active_model_serializers'
gem 'ember-cli-rails'
gem 'sdoc', '~> 0.4.0', group: :doc
group :development, :test do
  gem 'byebug'
end
group :development do
  gem 'web-console', '~> 2.0'
  gem 'sqlite3'
  gem 'spring'
end
group :production do 
  gem 'pg'
end
ruby '2.2.2'
gem 'rails_12factor', group: [:staging, :production]
