# Application bindings
bindd = SUPER, RETURN, Terminal, exec, uwsm-app -- xdg-terminal-exec --dir="$(omarchy-cmd-terminal-cwd)"
bindd = SUPER SHIFT, W, Browser, exec, uwsm-app -- brave

# Window navigation (vim bindings)
unbind = SUPER, H
unbind = SUPER, J
unbind = SUPER, K
unbind = SUPER, L
bind = SUPER, h, movefocus, l
bind = SUPER, j, movefocus, d
bind = SUPER, k, movefocus, u
bind = SUPER, l, movefocus, r

# Window management
unbind = SUPER, w
bind = SUPER, q, killactive

# Workspace navigation
unbind = SUPER, TAB
bind = SUPER, TAB, workspace, previous

# Cycle windows through different monitor workspaces
bind = SUPER SHIFT, RIGHT, movecurrentworkspacetomonitor, +1
bind = SUPER SHIFT, LEFT, movecurrentworkspacetomonitor, -1

# Swap window position (vim bindings)
unbind = SUPER SHIFT, LEFT
unbind = SUPER SHIFT, RIGHT
unbind = SUPER SHIFT, UP
unbind = SUPER SHIFT, DOWN
bindd = SUPER SHIFT, H, Swap window to the left, swapwindow, l
bindd = SUPER SHIFT, J, Swap window down, swapwindow, d
bindd = SUPER SHIFT, K, Swap window up, swapwindow, u
bindd = SUPER SHIFT, L, Swap window to the right, swapwindow, r
bindd = SUPER SHIFT, K, Show key bindings, exec, omarchy-menu-keybindings

# Screen recording
bindd = SUPER SHIFT, O, Stop screen recording, exec, omarchy-cmd-screenrecord

# Screenshot
# unbind = SUPER, p
# bind = SUPER, p, Screenshot, exec, omarchy capture screenshot region
