vim.keymap.set("n", "<leader>ga", ":G add %<CR>")
vim.keymap.set("n", "<leader>gr", ":G rm -rf %<CR>")
vim.keymap.set("n", "<leader>gg", ":G<CR>")
vim.keymap.set("n", "<leader>gc", ":G commit<CR>")
vim.keymap.set("n", "<leader>gp", ":G push<CR>")
vim.keymap.set("n", "<leader>gd", ":G diff<CR>")
vim.keymap.set("n", "<leader>gb", ":G blame<CR>")
